ORDER_LIST= "/api/orders/list"
ORDER_ADMIN_LIST= "/api/orders/admin/list"
ORDER_DETAIL= "/api/orders/detail"
ORDER_ADD= "/api/orders/add"
ORDER_STATUS_UPDATE = "/api/orders/update"
ORDER_TREND="/api/statics"