services:
  techhive-db:
    image: postgres:17
    container_name: "techhive-db"
    hostname: "techhive-db"
    environment:
      POSTGRES_USER: heinmin2maw
      POSTGRES_PASSWORD: heinmin2maw
      POSTGRES_DB: techhive-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}