services:
  techhive-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "techhive-app"
    depends_on:
      - techhive-db
    ports:
      - "8000:8000"

  techhive-db:
    image: postgres:17
    container_name: "techhive-db"
    restart: unless-stopped
    environment:
      POSTGRES_USER: heinmin2maw
      POSTGRES_PASSWORD: heinmin2maw
      POSTGRES_DB: techhive-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heinmin2maw -d techhive-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  db_data:
