services:
  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]
 
  db:
    container_name: techHive-db
    image: postgres:17
    ports:
      - "15432:5432"
    hostname: db
    environment:
      POSTGRES_DB: "techHive"
      POSTGRES_USER: "heinmin2maw"
      POSTGRES_PASSWORD: "heinmin2maw"
    volumes:
      - db-data:/data/postgres
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  db-data: {}