"""Added a new field 'handler_id' to order tbl

Revision ID: 271112da93cb
Revises: 50d208a010f8
Create Date: 2024-11-23 07:48:51.977640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271112da93cb'
down_revision: Union[str, None] = '50d208a010f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('handler_id', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'handler_id')
    # ### end Alembic commands ###
