"""new fields: expected_arrived_date and image url, added to order_product table

Revision ID: 2d22929ab8d2
Revises: 
Create Date: 2024-11-22 13:30:55.117653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d22929ab8d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('expected_arrived_date', sa.String(length=150), nullable=True))
    op.add_column('order_product', sa.Column('image_Url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'image_Url')
    op.drop_column('order_product', 'expected_arrived_date')
    # ### end Alembic commands ###
