"""Rename description field to context and new field embedding  added to Category Model

Revision ID: 4e388347a899
Revises: 9d39eebec588
Create Date: 2024-11-15 10:34:57.619808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e388347a899'
down_revision: Union[str, None] = '9d39eebec588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('related_context', sa.Text(), nullable=True))
    op.add_column('category', sa.Column('context_embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.drop_column('category', 'decription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('decription', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('category', 'context_embedding')
    op.drop_column('category', 'related_context')
    # ### end Alembic commands ###
