"""Added discount_percent_at_order field to OrderProduct Model

Revision ID: fb7301f406c6
Revises: 4e388347a899
Create Date: 2024-11-19 11:17:49.346675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7301f406c6'
down_revision: Union[str, None] = '4e388347a899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('discount_percent_at_order', sa.DECIMAL(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'discount_percent_at_order')
    # ### end Alembic commands ###
