ACCOUNT_LOGIN = "/api/access/login"
ACCOUNT_AUTH = "/api/authorize"
ACCOUNT_LOGOUT = "/api/access/logout"
ACCOUNT_REGISTER = "/api/access/signup"
TOKEN_REFRESH = "/api/access/refresh"

ACCOUNT_PROFILE = "/api/access/me"
ACCOUNT_LIST = "/api/users/list"
ACCOUNT_DELETE = "/api/users/delete/{user_id:uuid}"
ACCOUNT_DETAIL = "/api/users/detail/{user_id:uuid}"
ACCOUNT_UPDATE = "/api/users/update"
ACCOUNT_CREATE = "/api/users/add"